config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :users do
    collection do
      get 'me'
    end
  end

  resources :companies, except: :destroy

  resources :surveys do
    collection do
      post 'create_or_update'
      get 'gnrl_format'
      get 'answer_scale'
      get 'demo_quest'
      get 'proficiencies'
      get 'questionnaire'
      get 'participants'
      get 'evaluators'
      get ':token/responses/new', to: 'responses#new', as: :new_response
    end
    member do
      get 'section1'
      get 'section2'
      get 'section3'
      get 'confirmation'
    end
    resources :responses, only: [:index, :show, :new, :create]
  end
  get 'responses/all', to: 'responses#general'

  devise_scope :user do
    authenticated :user do
      root 'companies#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :response
  belongs_to :question
  has_and_belongs_to_many :options

  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_survey, only: [:index, :create, :destroy]
  before_action :set_response, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def general
    @responses = Response.all
  end

  def index
    @responses = @survey.responses
  end

  def show
  end

  def welcome
    @survey = Survey.find_by(token: params[:token])
  end

  def new
    @survey = Survey.find_by(token: params[:token])
    @response = Response.new
  end

  def create
    @response = Response.new(response_params)
    @response.user = current_or_guest_user
    if @response.save

    else
      render :new
    end
  end

  def destroy
    @response.destroy
    redirect_to responses_url, notice: 'Respuesta fue eliminada exitosamente.'
  end

  private

  def response_params
    params.require(:response)
          .permit(:survey_id, answers_attributes: [:id, :question_id, :_destroy,
                  :a_text, option_ids: []])
  end

  def set_survey
    @survey = Survey.find(params[:survey_id])
  end

  def set_response
    @response = Response.find(params[:id])
  end
end

app/views/responses/_responses.html.erb
<h1>Respuestas</h1>
<table class="table table-striped datatable">
  <thead>
    <tr>
      <th>Empresa</th>
      <th>Título</th>
      <th>Fecha de creación</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.survey.company.present? ? response.survey.company.name : '-' %></td>
        <td><%= response.survey.title %></td>
        <td><%= response.created_at.strftime('%d-%m-%Y') %></td>
        <td class="text-center">
          <%= link_to raw('<i class="fa fa-eye"></i>'),
            survey_response_path(response.survey, response), class: 'btn btn-info', title: 'Ver' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/responses/create.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <i class="fa fa-check"></i>
    Su encuesta ha sido completada y enviada satisfactoriamente. Gracias por su participación.
  </div>
</div>

app/views/responses/general.html.erb
<%= render 'responses' %>

app/views/responses/index.html.erb
<%= render 'responses' %>

app/views/responses/new.html.erb
<div id="main-wlcm" style="width:90%;margin:auto">
  <center><h1><%= @survey.title %></h1></center>
  <br><br>
  <p><%= raw @survey.instructions %></p>
  <br><br>
  <%= link_to 'Comenzar', '#', class: 'btn btn-primary pull-right', id: 'wlcm_next' %>
</div>

<div id="main-survey" style="width:90%;margin:auto;display:none">
  <%= simple_form_for(@response, url: survey_responses_path(@survey)) do |f| %>
    <%= f.error_notification %>
    <input type="hidden" name="response[survey_id]" value="<%= @survey.id %>">
    <% index = 0 %>

    <% if @survey.questions.demo.present? %>
      <div id="demographic-resp">
        <center><h2><%= @survey.demographic_title %></h2></center>
        <% @survey.questions.demo.each_with_index do |q, i| %>
          <input type="hidden" name="response[answers_attributes][<%=index%>][question_id]" value="<%= q.id %>">
          <h4><%= i + 1 %>. <%= q.title %></h4>
          <% q.options.each_with_index do |o| %>
            <div>
              <input type="radio" id="response_answers_attributes_<%=index%>_option_ids_<%=o.id%>"
                name="response[answers_attributes][<%=index%>][option_ids][]" value="<%=o.id%>" />
              <label for="response_answers_attributes_<%=index%>_option_ids_<%=o.id%>"><span></span><%= o.title if o.title.present? %></label>
            </div>
          <% end %>
          <% index += 1 %>
        <% end %>
        <%= link_to 'Aceptar y Continuar', '#', class: 'btn btn-danger pull-right', id: 'demo_next' %>
      </div>
    <% end %>
    <div id="questionnaire-resp" style="display:none">
      <table class="table table-bordered" style="width:100%">
        <thead>
          <tr>
            <th style="background-color:grey;color:#E22C29" colspan="2"><%= @survey.questionaire_title %></th>
            <% @survey.quest_default(@survey.questionnaire_scale).options.each do |qd| %>
              <th style="width:20%;text-align:center;background-color:#E22C29;color:white"><%= qd.title %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @survey.questions.where.not(q_type: [:demo, :text]).each_with_index do |q, i| %>
            <input type="hidden" name="response[answers_attributes][<%=index%>][question_id]" value="<%= q.id %>">
            <tr style="<%= i%2 == 0 ? 'background-color:lightgrey !important' : '' %>">
              <td><%= i + 1 %>.</td>
              <td><%= q.title %></td>
              <% q.options.each_with_index do |o, j| %>
                <td style="width:20%;text-align:center">
                  <input type="radio" id="response_answers_attributes_<%=index%>_option_ids_<%=o.id%>"
                    name="response[answers_attributes][<%=index%>][option_ids][]" value="<%=o.id%>" />
                  <label for="response_answers_attributes_<%=index%>_option_ids_<%=o.id%>"><span></span><%#= o.title if o.title.present? %></label>
                </td>
              <% end %>
            </tr>
            <% index += 1 %>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Aceptar y Continuar', '#', class: 'btn btn-danger pull-right', id: 'questions_next' %>
    </div>
    <div id="open-quest-resp" style="display:none">
      <center><h2><%= @survey.open_questions_title %></h2></center>
      <% @survey.questions.text.each_with_index do |q, i| %>
        <input type="hidden" name="response[answers_attributes][<%=index%>][question_id]" value="<%= q.id %>">
        <h4><%= i + 1 %>. <%= q.title %></h4>
        <textarea name="response[answers_attributes][<%=index%>][a_text]" class="form-control" rows="5"></textarea>
        <% index += 1 %>
      <% end %>
      <div class="form-actions row">
        <%= f.submit 'Enviar Encuesta', class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/responses/show.html.erb
<div style="width:90%;margin:auto">
    <center><h1><%= @response.survey.title %></h1></center>
    <p><%= @response.survey.description %></p>
    <input disabled type="hidden" name="response[survey_id]" value="<%= @response.survey.id %>">
    <% index = 0 %>
    <center><h2>Preguntas demográficas</h2></center>
    <% @response.survey.questions.ver_radio.each_with_index do |q, i| %>
      <input disabled type="hidden" name="response[answers_attributes][<%=index%>][question_id]"
        value="<%= q.id %>">
      <h4><%= i + 1 %>. <%= q.title %></h4>
      <% q.options.each_with_index do |o| %>
        <% if @response.answers.find_by(question:q).options.map(&:id).include?(o.id) %>
          <div>
            <input disabled type="radio" id="response_answers_attributes_<%=index%>_option_ids_<%=o.id%>"
              name="response[answers_attributes][<%=index%>][option_ids][]" value="<%=o.id%>"
              checked="<%= @response.answers.find_by(question:q).options.map(&:id).include?(o.id) %>"/>
            <label for="response_answers_attributes_<%=index%>_option_ids_<%=o.id%>"><span></span><%= o.title if o.title.present? %></label>
          </div>
        <% end %>
      <% end %>
      <% index += 1 %>
    <% end %>
    <center><h2>Cuestionario</h2></center>
    <% @response.survey.questions.hor_radio.each_with_index do |q, i| %>
      <input disabled type="hidden" name="response[answers_attributes][<%=index%>][question_id]"
        value="<%= q.id %>">
      <h4><%= i + 1 %>. <%= q.title %></h4>
      <% q.options.each_with_index do |o, j| %>
        <% if @response.answers.find_by(question:q).options.map(&:id).include?(o.id) %>
          <input disabled type="radio" id="response_answers_attributes_<%=index%>_option_ids_<%=o.id%>"
            name="response[answers_attributes][<%=index%>][option_ids][]" value="<%=o.id%>"
            checked="<%= @response.answers.find_by(question:q).options.map(&:id).include?(o.id) %>" />
          <label for="response_answers_attributes_<%=index%>_option_ids_<%=o.id%>"><span></span><%= o.title if o.title.present? %></label>
        <% end %>
      <% end %>
      <% index += 1 %>
    <% end %>
    <center><h2>Preguntas abiertas</h2></center>
    <% @response.survey.questions.text.each_with_index do |q, i| %>
      <input disabled type="hidden" name="response[answers_attributes][<%=index%>][question_id]" value="<%= q.id %>">
      <h4><%= i + 1 %>. <%= q.title %></h4>
      <textarea disabled name="response[answers_attributes][<%=index%>][a_text]" class="form-control" rows="5">
        <%= @response.answers.find_by(question: q).a_text %>
      </textarea>
      <% index += 1 %>
    <% end %>
</div>