config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :users do
    collection do
      get 'me'
    end
  end

  resources :companies, except: :destroy

  resources :surveys do
    collection do
      post 'create_or_update'
      get 'gnrl_format'
      get 'answer_scale'
      get 'demo_quest'
      get 'proficiencies'
      get 'questionnaire'
      get 'participants'
      get 'evaluators'
      get ':token/responses/new', to: 'responses#new', as: :new_response
    end
    member do
      get 'section1'
      get 'section2'
      get 'section3'
      get 'confirmation'
    end
    resources :responses, only: [:index, :show, :new, :create]
  end
  get 'responses/all', to: 'responses#general'

  devise_scope :user do
    authenticated :user do
      root 'companies#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :surveys

  has_one_attached :logo do |attachable|
    attachable.variant :medium, resize: "300x300>"
  end

  validates :name, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show]
  load_and_authorize_resource

  def index
    @companies = Company.all.order(name: :asc)
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_url, notice: 'Empresa fue creada exitosamente.'
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to companies_url, notice: 'Empresa fue actualizada exitosamente.'
    else
      render :edit
    end
  end

  private

  def company_params
    params.require(:company)
          .permit(:name, :logo, :ceo, :industry, :address, :region, :province,
                  :commune, :country, :identity_number, :url, :contact_email, :phone)
  end

  def set_company
    @company = Company.find(params[:id])
  end
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>
  <div class="text-center">
    <img height="300px" id="avatar" src="<%= (@company.logo.attached? and !@company.logo_updated_at_changed?)? @company.logo.variant(:medium) : image_pack_tag('media/images/default-profile.jpg') %>">
  </div>
  <div class="input-group user-img image-preview text-center" style="width:30%;left:35%">
    <input type="text" class="form-control image-preview-filename" disabled="disabled">
    <span class="input-group-btn">
      <button type="button" class="btn btn-default image-preview-clear">
        <span class="fa fa-trash"></span> Quitar
      </button>
      <div class="btn btn-default image-preview-input">
        <span class="fa fa-folder-open"></span>
        <span class="image-preview-input-title">Buscar</span>
        <%= f.input :logo, as: :file, label: false %>
      </div>
    </span>
  </div>
  <div class="form-group">
    <%= f.input :name, input_html: { class: 'form-control' },
      label: 'Nombre empresa' %>
  </div>
  <div class="form-group">
    <%= f.input :ceo, input_html: { class: 'form-control' },
      label: 'GERENTE GENERAL' %>
  </div>
  <div class="form-group">
    <%= f.input :industry, input_html: { class: 'form-control' },
      label: 'SECTOR INDUSTRIAL' %>
  </div>
  <div class="form-group">
    <%= f.input :address, input_html: { class: 'form-control' },
      label: 'DIRECCIÓN' %>
  </div>
  <div class="form-group">
    <%= f.input :region, input_html: { class: 'form-control' },
      label: 'REGIÓN' %>
  </div>
  <div class="form-group">
    <%= f.input :province, input_html: { class: 'form-control' },
      label: 'PROVINCIA' %>
  </div>
  <div class="form-group">
    <%= f.input :commune, input_html: { class: 'form-control' },
      label: 'COMUNA' %>
  </div>
  <div class="form-group">
    <%= f.input :country, input_html: { class: 'form-control' },
      label: 'PAÍS' %>
  </div>
  <div class="form-group">
    <%= f.input :identity_number, input_html: { class: 'form-control' },
      label: 'RUT' %>
  </div>
  <div class="form-group">
    <%= f.input :url, input_html: { class: 'form-control' },
      label: 'SITIO WEB' %>
  </div>
  <div class="form-group">
    <%= f.input :contact_email, input_html: { class: 'form-control' },
      label: 'CORREO ELECTRÓNICO DE CONTACTO' %>
  </div>
  <div class="form-group">
    <%= f.input :phone, input_html: { class: 'form-control' },
      label: 'TELÉFONO' %>
  </div>
  <div class="form-actions row">
    <%= f.submit 'Guardar', class: 'btn btn-danger pull-right' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<%= link_to raw("<i class='fa fa-arrow-left'></i>"), :back, class: 'btn btn-default' %>
<h3>EDITAR EMPRESA</h3>
<%= render 'form' %>

app/views/companies/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h3>Empresas</h3>
  </div>
  <div class="col-md-6 d-flex flex-row-reverse">
    <%= link_to raw("<i class='fa fa-plus'></i> Agregar"), new_company_path,
      class: 'btn btn-success' %>
  </div>
</div>
<br>
<table class="table table-bordered">
  <thead class="red-head">
    <tr>
      <th>NOMBRE</th>
      <th class="col-md-2"></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td class="text-center">
          <%= link_to raw('<i class="fa fa-eye"></i>'),
            company_path(c), 'data-turbolinks': false, class: "btn btn-info",
            title: "Ver" %>
          <%= link_to raw('<i class="fa fa-edit"></i>'),
            edit_company_path(c), 'data-turbolinks': false, title: "Editar",
            class: "btn btn-warning" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<%= link_to raw("<i class='fa fa-arrow-left'></i>"), :back, class: 'btn btn-default' %>
<h3>NUEVA EMPRESA</h3>
<%= render 'form' %>

app/views/companies/show.html.erb
<%= link_to raw("<i class='fa fa-arrow-left'></i>"), :back, class: 'btn btn-default' %>
<h3>PERFIL EMPRESA</h3><br>
<div style="margin:auto;width:70%">
<div class="row">
  <div class="col-md-6">
  <% if @company.logo.attached? %>
    <%= image_tag @company.logo.variant(:medium), style: 'height:300px;width:300px', alt: 'Company logo' %>
  <% else %>
    <%= image_pack_tag 'media/images/default-profile.jpg', style: 'height:300px;width:300px', alt: 'Company logo' %>
  <% end %>
  </div>
  <div class="col-md-6">
    <table class="table table-striped">
      <thead class="red-head">
        <th>Tipo encuesta</th>
        <th class="col-md-1 text-center">Cantidad</th>
      </thead>
      <tbody>
        <% Survey.s_types.each do |a, b| %>
          <tr>
            <td><%= a %></td>
            <td class="text-center"><%= Survey.where(company: @company, s_type: a).length %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<table class="table table-striped">
  <tbody>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Nombre:</td>
      <td><%= @company.name %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Gerente general:</td>
      <td><%= @company.ceo %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Sector industrial:</td>
      <td><%= @company.industry %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Dirección:</td>
      <td><%= @company.address %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Región:</td>
      <td><%= @company.region %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Provincia:</td>
      <td><%= @company.province %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Comuna:</td>
      <td><%= @company.commune %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">País:</td>
      <td><%= @company.country %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">RUT:</td>
      <td><%= @company.identity_number %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Sitio web:</td>
      <td><%= @company.url %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Correo electrónico de contacto:</td>
      <td><%= @company.contact_email %></td>
    </tr>
    <tr>
      <td class="col-md-4" style="background-color:#E22C29;color:white">Teléfono:</td>
      <td><%= @company.phone %></td>
    </tr>
  </tbody>
</table>
</div>