config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :users do
    collection do
      get 'me'
    end
  end

  resources :companies, except: :destroy

  resources :surveys do
    collection do
      post 'create_or_update'
      get 'gnrl_format'
      get 'answer_scale'
      get 'demo_quest'
      get 'proficiencies'
      get 'questionnaire'
      get 'participants'
      get 'evaluators'
      get ':token/responses/new', to: 'responses#new', as: :new_response
    end
    member do
      get 'section1'
      get 'section2'
      get 'section3'
      get 'confirmation'
    end
    resources :responses, only: [:index, :show, :new, :create]
  end
  get 'responses/all', to: 'responses#general'

  devise_scope :user do
    authenticated :user do
      root 'companies#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :company
  has_many :questions, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :proficiencies, dependent: :destroy
  has_many :question_defaults, dependent: :destroy
  has_many :options, through: :question_defaults
  has_many :employees, dependent: :destroy
  has_many :employee_responses, through: :employees, source: :response, class_name: 'Response'

  has_rich_text :description
  has_rich_text :welcome_msg
  has_rich_text :instructions
  has_rich_text :goodbye_msg

  validates :company_id, :s_type, presence: true

  enum s_type: [:ecl, :lef_360, :skw_360, :aap_360, :lej_360, :tes_pm, :exa_pm, :mbti]
  enum questionnaire_scale: [:n2, :n4, :n5, :n6, :n8]

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :proficiencies, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :question_defaults, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :employees, reject_if: :all_blank, allow_destroy: true

  before_destroy :check_status
  before_update :check_status
  after_create :set_question_defaults
  after_save :set_token

  def quest_default(quest_type)
    question_defaults.each do |qd|
      return qd if qd.q_type == quest_type
    end
  end

  def set_question_defaults
    unless question_defaults.present?
      Survey.questionnaire_scales.each do |a, b|
        qd = QuestionDefault.create(q_type: a)
        (1..a.gsub('n','').to_i).each do
          qd.options << Option.create(title:'')
        end
        question_defaults << qd
      end
    end
  end

  def check_status
    if status == 'Diseño'
      true
    else
      false
    end
  end

  def status
    if start_date.present? && end_date.present?
      now = DateTime.now
      if now > start_date
        if now < end_date
          return 'En Desarrollo'
        else
          return 'Cerrada'
        end
      end
    end
    'Diseño'
  end

  def aligment
    if default_alignment
      :vradio
    else
      :hor_radio
    end
  end

  def set_token
    self.token = SecureRandom.hex[0, 10].upcase + self.id.to_s
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  skip_before_action :authenticate_user!, only: :we_survey
  skip_before_action :verify_authenticity_token
  before_action :set_survey, only: [:show, :section1, :section2, :section3, :confirmation, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @title = 'REGISTRO'
    @surveys = Survey.all
  end

  def show
  end

  def section1
  end

  def section2
  end

  def section3
  end

  def confirmation
  end

  def new
    @survey = Survey.new
  end

  def edit
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to surveys_url, notice: 'Encuesta fue creada exitosamente.'
    else
      render :new
    end
  end

  def update
    if @survey.update(survey_params)
      redirect_to surveys_url, notice: 'Encuesta fue actualizada exitosamente.'
    else
      render :edit
    end
  end

  def create_or_update
    @survey = Survey.find_by(company_id: params[:survey][:company_id],
                             s_type: params[:survey][:s_type])
    if @survey.present?
      if @survey.update(survey_params)
        redirect_back(fallback_location: gnrl_format_surveys_url, notice: 'Datos guardados exitosamente')
      else
        redirect_back(fallback_location: gnrl_format_surveys_url, notice: 'Error al actualizar. Inténtelo nuevamente.')
      end
    else
      @survey = Survey.new(survey_params)
      if @survey.save
        redirect_back(fallback_location: gnrl_format_surveys_url, notice: 'Datos guardados exitosamente')
      else
        redirect_back(fallback_location: gnrl_format_surveys_url, notice: 'Error al crear. Inténtelo nuevamente.')
      end
    end
  end

  def gnrl_format
    @title = 'CONFIGURACIÓN - Formatos Generales'
    @current_company = params[:company_id]
    @current_s_type = params[:s_type]
    if params[:company_id].present?
      @survey = Survey.find_by(company_id: params[:company_id], s_type: params[:s_type])
      @survey = Survey.new unless @survey.present?
    else
      @survey = Survey.new
    end
    respond_to do |format|
      format.html
      format.js { render 'refill.js.erb' }
    end
  end

  def answer_scale
    @title = 'CONFIGURACIÓN - Formato Escala Respuesta'
    @current_company = params[:company_id]
    @current_s_type = params[:s_type]
    @current_q_scale = params[:q_scale]
    if params[:company_id].present?
      @survey = Survey.find_by(company_id: params[:company_id], s_type: params[:s_type])
      @survey = Survey.new unless @survey.present?
    else
      @survey = Survey.new
    end
    @survey.question_defaults.build unless @survey.question_defaults.present?
    respond_to do |format|
      format.html
      format.js { render 'refill.js.erb' }
    end
  end

  def demo_quest
    @title = 'CONFIGURACIÓN - Preguntas Demográficas'
    @quest_type = 'demo'
    @current_company = params[:company_id]
    @current_s_type = params[:s_type]
    if params[:company_id].present? && params[:s_type].present?
      @survey = Survey.find_by(company_id: params[:company_id], s_type: params[:s_type])
    end
    @survey = Survey.new unless @survey.present?
    respond_to do |format|
      format.html
      format.js { render 'refill.js.erb' }
    end
  end

  def proficiencies
    @title = 'CONFIGURACIÓN - Factores/Competencias'
    @current_company = params[:company_id]
    @current_s_type = params[:s_type]
    if params[:company_id].present?
      @survey = Survey.find_by(company_id: params[:company_id], s_type: params[:s_type])
      @survey = Survey.new unless @survey.present?
    else
      @survey = Survey.new
    end
    respond_to do |format|
      format.html
      format.js { render 'refill.js.erb' }
    end
  end

  def questionnaire
    @title = 'CONFIGURACIÓN - Preguntas'
    @current_company = params[:company_id]
    @current_s_type = params[:s_type]
    if params[:company_id].present?
      @survey = Survey.find_by(company_id: params[:company_id], s_type: params[:s_type])
      @survey = Survey.new unless @survey.present?
    else
      @survey = Survey.new
    end
    respond_to do |format|
      format.html
      format.js { render 'refill.js.erb' }
    end
  end

  def participants
    @title = 'CAPTURA DATOS - Lista de Participantes'
    @current_company = params[:company_id]
    @current_s_type = params[:s_type]
    if params[:company_id].present?
      @survey = Survey.find_by(company_id: params[:company_id], s_type: params[:s_type])
      @survey = Survey.new unless @survey.present?
    else
      @survey = Survey.new
    end
    respond_to do |format|
      format.html
      format.js { render 'refill.js.erb' }
    end
  end

  def evaluators
    @title = 'CAPTURA DATOS - Evaluadores 360°'
    @current_company = params[:company_id]
    @current_s_type = params[:s_type]
    if params[:company_id].present?
      @survey = Survey.find_by(company_id: params[:company_id], s_type: params[:s_type])
      @survey = Survey.new unless @survey.present?
    else
      @survey = Survey.new
    end
    respond_to do |format|
      format.html
      format.js { render 'refill.js.erb' }
    end
  end

  def destroy
    @survey.destroy
    redirect_to surveys_url, notice: 'Encuesta fue eliminada exitosamente.'
  end

  def we_survey
    @survey = Survey.find_by(token: params[:token], active: true)
    @response = Response.new
  end

  private

  def survey_params
    params.require(:survey)
          .permit(:title, :description, :active, :company_id, :s_type, :start_date,
                  :end_date, :welcome_msg, :instructions, :demographic_title,
                  :questionaire_title, :open_questions_title, :goodbye_msg,
                  :questionnaire_scale, :default_alignment,
                  questions_attributes: [:id, :order, :title, :scale, :q_type, :required,
                  :proficiency_id, :_destroy, options_attributes: [:id, :order, :title, :_destroy]],
                  proficiencies_attributes: [:id, :name, :description, :_destroy],
                  question_defaults_attributes: [:id, :q_type, :_destroy,
                  options_attributes: [:id, :order, :title, :_destroy]],
                  employees_attributes: [:id, :first_name, :last_name, :work_email,
                  :job_title, :work_area, :evaluator_id, :_destroy])
  end

  def set_survey
    @survey = Survey.find(params[:id])
  end
end

app/views/surveys/_answer_scale.html.erb
<%= simple_form_for(@survey, url: create_or_update_surveys_path, method: :post) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-6">
      <h3>Formato escala respuesta</h3>
    </div>
    <div class="col-md-6 d-flex flex-row-reverse">
      <%#= link_to_add_association raw("<i class='fa fa-plus'></i> Agregar"), f, :question_defaults,
        class: 'btn btn-success pull-right', partial: 'question_default_fields',
        'data-association-insertion-method': 'append',
        'data-association-insertion-node': '.table-items' %>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :company_id, collection: Company.all.collect {|p| [p.name, p.id]}.sort {|a,b| a<=>b},
        selected: @current_company, input_html: { class: 'form-control cia-scale', 'data-placeholder': 'Empresa' },
        label: 'Nombre empresa', required: true %>
    </div>
    <div class="col-md-6">
      <%= f.input :s_type, collection: Survey.s_types.collect { |ct| [Survey.human_attribute_name("s_type.#{ct[0]}"), ct[0]] },
        selected: @current_s_type, required: true, label: 'Tipo encuesta',
        input_html: { class: 'form-control cia-type' } %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :questionnaire_scale, collection: Survey.questionnaire_scales.collect { |ct| [Survey.human_attribute_name("questionnaire_scale.#{ct[0]}"), ct[0]] },
        checked: @current_q_scale, as: :radio_buttons, item_wrapper_class: 'radio-inline',
        required: true, label: 'ESCALA GENERAL CUESTIONARIO', input_html: { class: 'qscale' } %>
    </div>
    <div class="col-md-6">
      <%= f.input :default_alignment, collection: [['Vertical', true],['Horizontal', false]],
        as: :radio_buttons, item_wrapper_class: 'radio-inline',
        required: true, label: 'ALINEACIÓN ALTERNATIVAS', input_html: { class: 'dalignment' } %>
    </div>
  </div>
  <br>
  <table class="table table-bordered">
    <thead class="red-head">
      <tr>
        <th class="col-md-2">ESCALA GENERAL</th>
        <th>LEYENDA</th>
      </tr>
    </thead>
    <tbody class="table-items">
      <%= f.simple_fields_for :question_defaults do |question_default| %>
        <%= render 'question_default_fields', f: question_default if question_default.object.q_type == @current_q_scale %>
      <% end %>
    </tbody>
  </table>
  <%= f.submit 'Guardar', class: 'btn btn-danger pull-right' %>
<% end %>

app/views/surveys/_demo_quest.html.erb
<%= simple_form_for(@survey, url: create_or_update_surveys_path, method: :post) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-6">
      <h3>Preguntas demográficas</h3>
    </div>
    <div class="col-md-6 d-flex flex-row-reverse">
      <%= link_to_add_association raw("<i class='fa fa-plus'></i> Agregar"), f, :questions,
        class: 'btn btn-success pull-right', partial: 'question_fields',
        'data-association-insertion-method': 'append',
        'data-association-insertion-node': '.table-items' %>
      </div>
    </div>
    <br>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :company_id, collection: Company.all.collect {|p| [p.name, p.id]}.sort {|a,b| a<=>b},
        selected: @current_company, input_html: { class: 'form-control cia-demo', 'data-placeholder': 'Empresa' },
        label: 'Nombre empresa', required: true %>
    </div>
    <div class="col-md-6">
      <%= f.input :s_type, collection: Survey.s_types.collect { |ct| [Survey.human_attribute_name("s_type.#{ct[0]}"), ct[0]] },
        selected: @current_s_type, required: true, label: 'Tipo encuesta',
        input_html: { class: 'form-control cia-type' } %>
    </div>
  </div>
  <br>
  <table class="table table-bordered">
    <thead class="red-head">
      <tr>
        <th class="col-md-1">ORDEN</th>
        <th>PREGUNTA</th>
        <th></th>
      </tr>
    </thead>
    <tbody class="table-items">
      <%= f.simple_fields_for :questions do |question| %>
        <% @q_id = DateTime.now.to_s.gsub('-','').gsub(':','') + rand(10000).to_s %>
        <%= render partial: 'question_fields', locals: {f: question, questid: @q_id} if question.object.demo? %>
      <% end %>
    </tbody>
  </table>
  <%= f.submit 'Guardar', class: 'btn btn-danger pull-right' %>
<% end %>

app/views/surveys/_employee_fields.html.erb
<tr class="nested-fields">
  <td class="text-center"><%= f.input :id, disabled: true, label: false %></td>
  <td>
    <%= f.input :first_name, input_html: { class: 'form-control' }, required: true,
      label: false %>
  </td>
  <td>
    <%= f.input :last_name, input_html: { class: 'form-control' }, required: true,
      label: false %>
  </td>
  <td>
    <%= f.input :work_email, input_html: { class: 'form-control' }, required: true,
      label: false %>
  </td>
  <td>
    <%= f.input :job_title, input_html: { class: 'form-control' }, required: true,
      label: false %>
  </td>
  <td>
    <%= f.input :work_area, input_html: { class: 'form-control' }, required: true,
      label: false %>
  </td>
  <% if params[:action] == 'participants' %>
    <td></td>
  <% else %>
    <td>
      <%= f.input :evaluator_id, collection: Employee.where.not(id: f.object.id).collect { |e| [e.full_name + ' - ' + e.job_title, e.id] },
        input_html: { class: 'form-control' }, required: true, label: false %>
    </td>
  <% end %>
  <td class="text-center">
    <%= link_to_remove_association "<i class='fa fa-trash'></i>".html_safe,
      f, class: 'btn btn-danger', title: 'Eliminar' %>
  </td>
</tr>

app/views/surveys/_evaluators.html.erb
<%= simple_form_for(@survey, url: create_or_update_surveys_path, method: :post) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-6">
      <h3>Evaluadores 360°</h3>
    </div>
    <div class="col-md-6 d-flex flex-row-reverse">
      <%= link_to_add_association raw("<i class='fa fa-plus'></i> Agregar"), f, :employees,
        class: 'btn btn-success pull-right', partial: 'employee_fields',
        'data-association-insertion-method': 'append',
        'data-association-insertion-node': '.table-items' %>
      </div>
    </div>
    <br>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :company_id, collection: Company.all.collect {|p| [p.name, p.id]}.sort {|a,b| a<=>b},
        selected: @current_company, input_html: { class: 'form-control cia-eval', 'data-placeholder': 'Empresa' },
        label: 'Nombre empresa', required: true %>
    </div>
    <div class="col-md-6">
      <%= f.input :s_type, collection: Survey.s_types.collect { |ct| [Survey.human_attribute_name("s_type.#{ct[0]}"), ct[0]] },
        selected: @current_s_type, required: true, label: 'Tipo encuesta',
        input_html: { class: 'form-control cia-type' } %>
    </div>
  </div>
  <br>
  <table class="table table-bordered">
    <thead class="red-head">
      <tr>
        <th>ID</th>
        <th>NOMBRES</th>
        <th>APELLIDOS</th>
        <th>EMAIL</th>
        <th>CARGO</th>
        <th>ÁREA</th>
        <th>EVALUADOR</th>
        <th></th>
      </tr>
    </thead>
    <tbody class="table-items">
      <%= f.simple_fields_for :employees do |employee| %>
        <%= render 'employee_fields', f: employee %>
      <% end %>
    </tbody>
  </table>
  <%= f.submit 'Guardar', class: 'btn btn-danger pull-right' %>
<% end %>

app/views/surveys/_form.html.erb
<%= f.error_notification %>
<div class="form-group row">
  <%= f.input :title, input_html: { class: 'form-control',
    placeholder: 'Título' }, label: false, required: true %>
</div>
<div class="form-group row">
  <%= f.rich_text_area :description, input_html: { class: 'form-control',
    rows: 5, placeholder: 'Descripción', ckeditor: { toolbar: 'Full' } },
    label: false, required: true, as: :ckeditor %>
</div>
<div class="form-group row">
  <div>
    <input type="radio" id="survey_active_true" name="survey[active]" value="true"
      checked="<%= @survey.active %>"/>
    <label for="survey_active_true"><span></span>Activo</label>
  </div>
  <div>
    <input type="radio" id="survey_active_false" name="survey[active]" value="false"
      checked="<%= @survey.active %>"/>
    <label for="survey_active_false"><span></span>Inactivo</label>
  </div>
</div>
<div class="form-group row">
  <%= f.simple_fields_for :questions do |question| %>
    <%= render 'question_fields', f: question %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'Agregar pregunta', f, :questions, class: 'btn-main text-center', style: 'margin-top:20px' %>
  </div>
</div>
<div class="form-actions row">
  <%= f.button :submit, class: 'btn btn-success' %>
</div>

app/views/surveys/_option_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= f.input :order, input_html: { class: 'form-control',
      placeholder: 'Orden' }, required: true, label: false %>
      <p>CI: <%= f.options[:child_index] %></p>
  </td>
  <td>
    <%= f.input :title, input_html: { class: 'form-control',
      placeholder: 'Título' }, required: true, label: false %>
  </td>
  <% if params[:action] == 'demo_quest' %>
    <td class="text-center">
      <%= link_to_remove_association "<i class='fa fa-trash'></i>".html_safe,
        f, class: 'btn btn-danger', title: 'Eliminar' %>
    </td>
  <% end %>
</tr>

app/views/surveys/_proficiency_fields.html.erb
<tr class="nested-fields">
  <td class="text-center"><%= f.input :id, disabled: true, label: false %></td>
  <td>
    <%= f.input :name, input_html: { class: 'form-control',
      placeholder: 'Nombre' }, required: true, label: false %>
  </td>
  <td>
    <%= f.input :description, input_html: { class: 'form-control',
      placeholder: 'Descripción' }, required: true, label: false %>
  </td>
  <td class="text-center">
    <%= link_to_remove_association "<i class='fa fa-trash'></i>".html_safe,
      f, class: 'btn btn-danger', title: 'Eliminar' %>
  </td>
</tr>

app/views/surveys/_question_default_fields.html.erb
<div class="nested-fields">
  <%= f.simple_fields_for :options do |option| %>
    <%= render 'option_fields', f: option %>
  <% end %>
</div>

app/views/surveys/_questionnaire.html.erb
<%= simple_form_for(@survey, url: create_or_update_surveys_path, method: :post) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-6">
      <h3>Preguntas</h3>
    </div>
    <div class="col-md-6 d-flex flex-row-reverse">
      <%= link_to_add_association raw("<i class='fa fa-plus'></i> Agregar"), f, :questions,
        class: 'btn btn-success pull-right', partial: 'questionnaire_fields',
        'data-association-insertion-method': 'append',
        'data-association-insertion-node': '.table-items' %>
      </div>
    </div>
    <br>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :company_id, collection: Company.all.collect {|p| [p.name, p.id]}.sort {|a,b| a<=>b},
        selected: @current_company, input_html: { class: 'form-control cia-quest', 'data-placeholder': 'Empresa' },
        label: 'Nombre empresa', required: true %>
    </div>
    <div class="col-md-6">
      <%= f.input :s_type, collection: Survey.s_types.collect { |ct| [Survey.human_attribute_name("s_type.#{ct[0]}"), ct[0]] },
        selected: @current_s_type, required: true, label: 'Tipo encuesta',
        input_html: { class: 'form-control cia-type' } %>
    </div>
  </div>
  <br>
  <table class="table table-bordered">
    <thead class="red-head">
      <tr>
        <th>ORDEN</th>
        <th>PREGUNTAS</th>
        <th>ESCALA</th>
        <th>FACTOR/COMPETENCIA</th>
        <th>DISEÑO</th>
        <th></th>
      </tr>
    </thead>
    <tbody class="table-items">
      <%= f.simple_fields_for :questions do |question| %>
        <%= render 'questionnaire_fields', f: question if question.object.q_type != 'demo' %>
      <% end %>
    </tbody>
  </table>
  <%= f.submit 'Guardar', class: 'btn btn-danger pull-right' %>
<% end %>

app/views/surveys/edit.html.erb
<div class="row">
  <h1 class="text-center">Editar encuesta</h1>
</div>

<%= simple_form_for(@survey) do |f| %>
  <%= render 'form', f:f %>
<% end %>

app/views/surveys/evaluators.html.erb
<div class="config-container">
  <%= render 'evaluators' %>
</div>

app/views/surveys/gnrl_format.html.erb
<div class="config-container">
  <%= render 'gnrl_format' %>
</div>

app/views/surveys/section3.html.erb
<div style="width:90%;margin:auto">
  <center><h2>Preguntas abiertas</h2></center>
  <br><br>
  <% @survey.questions.text.order(order: :asc).each_with_index do |q, i| %>
    <div class="row">
      <h4><%= i + 1 %>. <%= '* ' if q.required %><%= q.title %></h4>
      <textarea class="form-control" rows="5"></textarea>
    </div>
    <br>
  <% end %>
  <br><br>
  <%= link_to 'Siguiente', confirmation_survey_path, class: 'btn btn-primary pull-right' %>
</div>

app/views/surveys/show.html.erb
<div style="width:90%;margin:auto">
  <center><h1><%= @survey.title %></h1></center>
  <br><br>
  <p><%= @survey.instructions %></p>
  <br><br>
  <%= link_to 'Comenzar', section1_survey_path, class: 'btn btn-primary pull-right' %>
</div>