config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :users do
    collection do
      get 'me'
    end
  end

  resources :companies, except: :destroy

  resources :surveys do
    collection do
      post 'create_or_update'
      get 'gnrl_format'
      get 'answer_scale'
      get 'demo_quest'
      get 'proficiencies'
      get 'questionnaire'
      get 'participants'
      get 'evaluators'
      get ':token/responses/new', to: 'responses#new', as: :new_response
    end
    member do
      get 'section1'
      get 'section2'
      get 'section3'
      get 'confirmation'
    end
    resources :responses, only: [:index, :show, :new, :create]
  end
  get 'responses/all', to: 'responses#general'

  devise_scope :user do
    authenticated :user do
      root 'companies#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="social row vertical-align">
    <div class="col-md-4 logo">
      <div class="col-md-12">
        <%= image_pack_tag("media/images/logo_red.png", height: '50') %>
      </div>
      <div class="col-md-12">
        excelencia. impacto. productividad.
      </div>
    </div>
    <div class="col-md-4 text-center">
      <ul class="icons d-flex justify-content-center gap-3">
        <li><%= link_to raw("<i class='fab fa-twitter fa-fw'></i>"), "https://twitter.com/comtraining" %></li>
        <li><%= link_to raw("<i class='fab fa-facebook fa-fw'></i>"), "https://www.facebook.com/Comtraining-201714396539810/" %></li>
        <li><%= link_to raw("<i class='fa fa-envelope fa-fw'></i>"), "mailto:info@comtraining.cl" %></li>
        <li><%= link_to raw("<i class='fab fa-linkedin fa-fw'></i>"), "https://www.linkedin.com/company/comtraining-consulting-&-coaching" %></li>
      </ul>
    </div>
    <div class="col-md-4 text-right">
      <ul>
        <li>Copyright &copy; <%= Date.current.year %></li>
        <li>Todos los derechos reservados</li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to root_url, 'data-turbolinks': false, class: 'navbar-brand' do %>
      <%= image_pack_tag("media/images/logo_red.png", height: '50') %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapse" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="navbar-nav me-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="config-menu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Configuración
          </a>
          <ul class="dropdown-menu" aria-labelledby="config-menu">
            <li><%= link_to 'Empresas', companies_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Formatos Generales', gnrl_format_surveys_path, 'data-turbolinks': false, class: 'dropdown-item' %></li>
            <li><%= link_to 'Formato Escala Respueta', answer_scale_surveys_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Preguntas Demográficas', demo_quest_surveys_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Factores/Competencias', proficiencies_surveys_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Preguntas', questionnaire_surveys_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item"><%= link_to 'Registro', surveys_path, class: 'nav-link' %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="capture-menu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Captura datos
          </a>
          <ul class="dropdown-menu" aria-labelledby="capture-menu">
            <li><%= link_to 'Lista de Participantes', participants_surveys_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Evaluadores 360', evaluators_surveys_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="reports-menu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Reportes
          </a>
          <ul class="dropdown-menu" aria-labelledby="reports-menu">
            <li><%= link_to 'Por Dato Demográfico', '#', class: 'dropdown-item' %></li>
            <li><%= link_to 'Por Factor/Competencia', '#', class: 'dropdown-item' %></li>
            <li><%= link_to 'Por Gerencia/Áreantas', '#', class: 'dropdown-item' %></li>
            <li><%= link_to 'Por Pregunta', '#', class: 'dropdown-item' %></li>
            <li><%= link_to 'Por Evaluado', '#', class: 'dropdown-item' %></li>
            <li><%= link_to 'Comparativo Histórico', '#', class: 'dropdown-item' %></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="account-menu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.full_name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="account-menu">
            <li>
              <%= link_to 'Perfil', me_users_path, class: 'dropdown-item' %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Encuestas - Comtraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <% offset = "180px" %>
      <%= render "layouts/menu" %>
    <% else %>
      <% offset = "104px" %>
    <% end %>
    <div id="notice">
      <%= bootstrap_flash %>
    </div>
    <div class="container-fluid p-5" style="min-height: calc(100vh - <%= offset %>)">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>